import './styles/index.scss'

import FeatureFlagProvider from '@/app/components/FeatureFlagProvider'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import Nav from '@/app/components/Nav'
import flagsmith from 'flagsmith/isomorphic'
import { getDefaultUser } from '@/app/utils/getDefaultUser'
import { getTraits } from '@/app/utils/getTraits'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Flagsmith with Next.js',
  description: 'Generated by create next app',
}
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const defaultUser = await getDefaultUser()

  await flagsmith.init({
    // The layout is rendered on the server, so we need to use the server environment ID.
    // This is because the client environment ID is not available until the client is rendered.
    environmentID: process.env.FLAGSMITH_ENVIRONMENT_ID || '',
    identity: defaultUser?.id,
    traits: getTraits(defaultUser),
  })

  const serverState = flagsmith.getState()

  // Check this out in the terminal console. It can also appear in the browser console
  // with a "Server" label prefixed.
  console.log('serverState', serverState)

  return (
    <html lang='en'>
      <FeatureFlagProvider serverState={serverState}>
        <body className={inter.className}>
          <Nav defaultUser={defaultUser} />
          {children}
        </body>
      </FeatureFlagProvider>
    </html>
  )
}
