import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/index.scss'
import Nav from '@/app/components/Nav'
import useDefaultUser from '@/app/hooks/useDefaultUser'
import { createFlagsmithInstance } from 'flagsmith/isomorphic'
import FeatureFlagProvider from '@/app/components/FeatureFlagProvider'
import getTraits from '@/app/utils/getTraits'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Flagsmith with Next.js',
  description: 'Generated by create next app',
}
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const defaultUser = useDefaultUser()
  const flagsmith = createFlagsmithInstance()
  await flagsmith.init({
    environmentID: 'GjAAsnDhzDRoUCmji3p8Sh',
    identity: defaultUser?.id,
    api: 'http://localhost:8000/api/v1/',
    traits: getTraits(defaultUser),
  })
  const serverState = flagsmith.getState()
  return (
    <html lang='en'>
      <FeatureFlagProvider serverState={serverState}>
        <body className={inter.className}>
          <Nav defaultUser={defaultUser} />
          {children}
        </body>
      </FeatureFlagProvider>
    </html>
  )
}
